[build]
  base = "/"
  publish = "dist"
  command = "npm run build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18.x"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8888
  publish = "dist"